#####################################################################################################
# Bienvenido, este es el archivo de configuración donde se encuentran todos los parámetros de Tidal #
#####################################################################################################
# Origen: https://raw.githubusercontent.com/Inetol/static/rolling/tidal/.tidal.yml


# Versión: int
# ! NO MODIFICAR
version: 2

# Update: bool
# - Esto habilitará la actualización del archivo de configuración cuando haya una nueva versión disponible.
# - Si quieres asegurarte de que tu proyecto siempre esté funcionando, deberías cambiar el valor a "false".
#
# ! NO OBSTANTE, cualquier nueva actualización del fichero de configuración puede hacer que la versión local produzca problemas con Tidal.
# ! Se recomienda encarecidamente realizar una revisión manual y aplicar las nuevas actualizaciones que haya disponibles de vez en cuando.
update: true

## Apartado: Tidal
tidal:
  # Runtime: string
  # - Aquí puedes establecer el entorno que necesita tu proyecto en el slot.
  #
  # ? Valores disponibles: "java", "deno" y "node"
  #runtime: none
  runtime: none

## Apartado: Slot
slot:
  # Runtime: string
  # - Ubicación del fichero maestro a ejecutar.
  #file: "src/index.js"
  file: "src/index.js"

  ## Apartado: GIT
  git:
    # Enabled: bool
    # - Habilita GIT para mantener los ficheros locales actualizados con un repositorio remoto.
    #
    # ! NO SE RECOMIENDA HABILITAR SI NO SABES QUE ESTÁS HACIENDO. ESTA ACCIÓN PUEDE PRODUCIR PERDIDA DE DATOS.
    #enabled: false
    enabled: false

    # URL: string
    # - URL del repositorio remoto.
    #
    # ? :user | Usuario
    # ? :repo | Repositorio
    # ! Este campo solo tendrá efecto si está habilitado GIT.
    #url: "https://github.com/:user/:repo"
    url: "https://github.com/:user/:repo"

    # Token: string
    # - En caso de tener un repositorio privado, Tidal va a necesitar un token de acceso al repositorio remoto de tu proveedor.
    #
    # ? GitHub: https://docs.github.com/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token#creating-a-token
    # ? GitLab: https://docs.gitlab.com/ee/user/profile/personal_access_tokens.html#create-a-personal-access-token
    # ! Este campo solo tendrá efecto si está habilitado GIT.
    #token: ""
    token: ""

    # Branch: string
    # - La rama del repositorio remoto a utilizar.
    #
    # ! Este campo solo tendrá efecto si está habilitado GIT.
    #branch: "main"
    branch: "main"